### ISSUE TITLE
客户端和命令行都有问题

### ISSUE THREAD

**Issue by jiahe224** [yihong0618/Kindle_download_helper#106]
1.win
可正常获取下载列表，但报错：
404 Client Error: Not Found for url: https://www.amazon.cn/error
2.命令行
无报错信息，也未成功下载，命令形如：
python3 kindle.py 'csr_value' --cookie 'cook_value' --dedrm --cn
文档给出的命令是Linux下的，win里powershell中无法定义变量

**Comment by yihong0618** [comment]
@jiahe224 我今天晚上或者明天看一下。
理论正常获取下载列表可以下载, 我这边测了下没问题。
![image](https://user-images.githubusercontent.com/15976103/219312934-d58f52ff-f56d-4a34-8651-bd4b1bba6793.png)

你能提供更多的 cli 报错信息么？

**Comment by jiahe224** [comment]
@yihong0618 输完命令回车后，没有任何反应，自动开始新的命令输入，贴出完整命令安全吗（带cookie等）

**Comment by yihong0618** [comment]
不安全，windows 的话没任何反应试试 python 代替 python3

**Comment by jiahe224** [comment]
@yihong0618 用的就是'python'，只装了python 3

**Comment by yihong0618** [comment]
你单独输入 `python` 试试看看是否进入 repl

**Comment by jiahe224** [comment]
可以的

**Comment by zoenbo** [comment]
大佬，为何我用WIN的GUI始终无法获取下载列表呢？cookie和csrfToken都是按教程填写。

**Comment by yihong0618** [comment]
> 大佬，为何我用WIN的GUI始终无法获取下载列表呢？cookie和csrfToken都是按教程填写。

有报错么？（需要有实体设备，没有实体设备只能使用置顶的方式

**Comment by ChenhaoranY** [comment]
![image](https://github.com/yihong0618/Kindle_download_helper/assets/115782448/ae8caac5-ebce-4bb3-afae-8fc0f2398a1d)
我也遇到相同的问题
[2024-03-20 11:54:11,521]INFO - Amazon bot check detected, sleep 3 sec
[2024-03-20 11:54:15,019]ERROR - 404 Client Error:  for url: https://www.amazon.co.jp/error
[2024-03-20 11:54:15,019]ERROR - Title: 祈りの国のリリエール３ (GAノベル), Asin: B0C22NBTYW download failed
[2024-03-20 11:54:41,068]INFO - Amazon bot check detected, sleep 3 sec
[2024-03-20 11:55:03,778]INFO - Amazon bot check detected, sleep 3 sec
显示下载成功但实际上没有任何的下载内容。

**Comment by yihong0618** [comment]
@ChenhaoranY 是只有一本书对吧？我今天发个版本。

**Comment by yihong0618** [comment]
> ![image](https://private-user-images.githubusercontent.com/115782448/314635707-ae8caac5-ebce-4bb3-afae-8fc0f2398a1d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5ODMxODQsIm5iZiI6MTcxMDk4Mjg4NCwicGF0aCI6Ii8xMTU3ODI0NDgvMzE0NjM1NzA3LWFlOGNhYWM1LWViY2UtNGJiMy1hZmFlLThmYzBmMjM5OGExZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMVQwMTAxMjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYWE2NDBlMjEzMmIwNmMxODc0YzAzNjUxYjI5ZWIwZmY2NzM3YmZjMTM1YmVkYTMyOTQ2MWY0MDg2NmMyYzg5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dnTz_RWUMt4hkdOaieTUK1w1rln8LUcaR5UXtzul0dI) 我也遇到相同的问题 [2024-03-20 11:54:11,521]INFO - Amazon bot check detected, sleep 3 sec [2024-03-20 11:54:15,019]ERROR - 404 Client Error: for url: https://www.amazon.co.jp/error [2024-03-20 11:54:15,019]ERROR - Title: 祈りの国のリリエール３ (GAノベル), Asin: B0C22NBTYW download failed [2024-03-20 11:54:41,068]INFO - Amazon bot check detected, sleep 3 sec [2024-03-20 11:55:03,778]INFO - Amazon bot check detected, sleep 3 sec 显示下载成功但实际上没有任何的下载内容。

GUI 可能不行，你用置顶的 no_kindle 方式试试

**Comment by ChenhaoranY** [comment]
Requirement already satisfied: requests in d:\programdata\anaconda3\lib\site-packages (from -r requirements.txt (line 1)) (2.31.0)
Collecting browser-cookie3 (from -r requirements.txt (line 2))
  Obtaining dependency information for browser-cookie3 from https://files.pythonhosted.org/packages/0a/0d/0fa3b3a13870a9beb4739449e2fc0071d66715b5c300783966541867457c/browser_cookie3-0.19.1-py3-none-any.whl.metadata
  Using cached browser_cookie3-0.19.1-py3-none-any.whl.metadata (632 bytes)
Collecting mobi (from -r requirements.txt (line 3))
  Using cached mobi-0.3.3.tar.gz (90 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting amazon.ion (from -r requirements.txt (line 4))
  Using cached amazon.ion-0.12.0.tar.gz (674 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [130 lines of output]
      git version 2.43.0.windows.1
      cmake version 3.20.2

      CMake suite maintained and supported by Kitware (kitware.com/cmake).
      Cloning into 'ion-c'...
      Submodule 'deps/google-test' (https://github.com/google/googletest.git) registered for path 'deps/google-test'
      Submodule 'ion-tests' (https://github.com/amazon-ion/ion-tests.git) registered for path 'ion-tests'
      Submodule 'tools/ion-bench/deps/google-benchmark' (https://github.com/google/benchmark.git) registered for path 'tools/ion-bench/deps/google-benchmark'
      Submodule 'tools/ion-bench/deps/json-c' (https://github.com/json-c/json-c.git) registered for path 'tools/ion-bench/deps/json-c'
      Submodule 'tools/ion-bench/deps/libcbor' (https://github.com/PJK/libcbor.git) registered for path 'tools/ion-bench/deps/libcbor'
      Submodule 'tools/ion-bench/deps/msgpack-c' (https://github.com/msgpack/msgpack-c.git) registered for path 'tools/ion-bench/deps/msgpack-c'
      Submodule 'tools/ion-bench/deps/yyjson' (https://github.com/ibireme/yyjson.git) registered for path 'tools/ion-bench/deps/yyjson'
      Cloning into 'C:/Users/10537/AppData/Local/Temp/pip-install-kr487q86/amazon-ion_ae72437b5ff045c299c17f4f2c51981a/ion-c/deps/google-test'...
      Cloning into 'C:/Users/10537/AppData/Local/Temp/pip-install-kr487q86/amazon-ion_ae72437b5ff045c299c17f4f2c51981a/ion-c/ion-tests'...
      Cloning into 'C:/Users/10537/AppData/Local/Temp/pip-install-kr487q86/amazon-ion_ae72437b5ff045c299c17f4f2c51981a/ion-c/tools/ion-bench/deps/google-benchmark'...
      Cloning into 'C:/Users/10537/AppData/Local/Temp/pip-install-kr487q86/amazon-ion_ae72437b5ff045c299c17f4f2c51981a/ion-c/tools/ion-bench/deps/json-c'...
      Cloning into 'C:/Users/10537/AppData/Local/Temp/pip-install-kr487q86/amazon-ion_ae72437b5ff045c299c17f4f2c51981a/ion-c/tools/ion-bench/deps/libcbor'...
      Cloning into 'C:/Users/10537/AppData/Local/Temp/pip-install-kr487q86/amazon-ion_ae72437b5ff045c299c17f4f2c51981a/ion-c/tools/ion-bench/deps/msgpack-c'...
      Cloning into 'C:/Users/10537/AppData/Local/Temp/pip-install-kr487q86/amazon-ion_ae72437b5ff045c299c17f4f2c51981a/ion-c/tools/ion-bench/deps/yyjson'...
      Submodule path 'deps/google-test': checked out '783d00fd19865fcbc3065e3fb3e17144761fcf5a'
      Submodule path 'ion-tests': checked out 'b6b52537bff275045531463443bb89bd1e15ee7b'
      Submodule path 'tools/ion-bench/deps/google-benchmark': checked out 'b177433f3ee2513b1075140c723d73ab8901790f'
      Submodule path 'tools/ion-bench/deps/json-c': checked out 'd0f32a5a43d1b9dc0b2cd6af310e5f09b97c3423'
      Submodule path 'tools/ion-bench/deps/libcbor': checked out '8fba9a6fb36cae03539e4f6e15c22e60ced52fb3'
      Submodule 'doxygen-theme' (https://github.com/nnen/doxygen-theme.git) registered for path 'tools/ion-bench/deps/libcbor/doxygen-theme'
      Cloning into 'C:/Users/10537/AppData/Local/Temp/pip-install-kr487q86/amazon-ion_ae72437b5ff045c299c17f4f2c51981a/ion-c/tools/ion-bench/deps/libcbor/doxygen-theme'...
      Submodule path 'tools/ion-bench/deps/libcbor/doxygen-theme': checked out '46111c61a9f49b7a9886127e679d4317478fab1c'
      Submodule path 'tools/ion-bench/deps/msgpack-c': checked out 'cd67366b7f598c178cfbe0382274ff3f2bb90cac'
      Submodule path 'tools/ion-bench/deps/yyjson': checked out '4950308edb2e1c722f475635176e901656646520'
      CMake Error: Could not create named generator Visual Studio 17 2022

      Generators
        Visual Studio 16 2019        = Generates Visual Studio 2019 project files.
                                       Use -A option to specify architecture.
        Visual Studio 15 2017 [arch] = Generates Visual Studio 2017 project files.
                                       Optional [arch] can be "Win64" or "ARM".
        Visual Studio 14 2015 [arch] = Generates Visual Studio 2015 project files.
                                       Optional [arch] can be "Win64" or "ARM".
        Visual Studio 12 2013 [arch] = Generates Visual Studio 2013 project files.
                                       Optional [arch] can be "Win64" or "ARM".
        Visual Studio 11 2012 [arch] = Generates Visual Studio 2012 project files.
                                       Optional [arch] can be "Win64" or "ARM".
        Visual Studio 10 2010 [arch] = Generates Visual Studio 2010 project files.
                                       Optional [arch] can be "Win64" or "IA64".
        Visual Studio 9 2008 [arch]  = Generates Visual Studio 2008 project files.
                                       Optional [arch] can be "Win64" or "IA64".
        Borland Makefiles            = Generates Borland makefiles.
      * NMake Makefiles              = Generates NMake makefiles.
        NMake Makefiles JOM          = Generates JOM makefiles.
        MSYS Makefiles               = Generates MSYS makefiles.
        MinGW Makefiles              = Generates a make file for use with
                                       mingw32-make.
        Green Hills MULTI            = Generates Green Hills MULTI files
                                       (experimental, work-in-progress).
        Unix Makefiles               = Generates standard UNIX makefiles.
        Ninja                        = Generates build.ninja files.
        Ninja Multi-Config           = Generates build-<Config>.ninja files.
        Watcom WMake                 = Generates Watcom WMake makefiles.
        CodeBlocks - MinGW Makefiles = Generates CodeBlocks project files.
        CodeBlocks - NMake Makefiles = Generates CodeBlocks project files.
        CodeBlocks - NMake Makefiles JOM
                                     = Generates CodeBlocks project files.
        CodeBlocks - Ninja           = Generates CodeBlocks project files.
        CodeBlocks - Unix Makefiles  = Generates CodeBlocks project files.
        CodeLite - MinGW Makefiles   = Generates CodeLite project files.
        CodeLite - NMake Makefiles   = Generates CodeLite project files.
        CodeLite - Ninja             = Generates CodeLite project files.
        CodeLite - Unix Makefiles    = Generates CodeLite project files.
        Eclipse CDT4 - NMake Makefiles
                                     = Generates Eclipse CDT 4.0 project files.
        Eclipse CDT4 - MinGW Makefiles
                                     = Generates Eclipse CDT 4.0 project files.
        Eclipse CDT4 - Ninja         = Generates Eclipse CDT 4.0 project files.
        Eclipse CDT4 - Unix Makefiles= Generates Eclipse CDT 4.0 project files.
        Kate - MinGW Makefiles       = Generates Kate project files.
        Kate - NMake Makefiles       = Generates Kate project files.
        Kate - Ninja                 = Generates Kate project files.
        Kate - Unix Makefiles        = Generates Kate project files.
        Sublime Text 2 - MinGW Makefiles
                                     = Generates Sublime Text 2 project files.
        Sublime Text 2 - NMake Makefiles
                                     = Generates Sublime Text 2 project files.
        Sublime Text 2 - Ninja       = Generates Sublime Text 2 project files.
        Sublime Text 2 - Unix Makefiles
                                     = Generates Sublime Text 2 project files.

      CMake Warning:
        No source or binary directory provided.  Both will be assumed to be the
        same as the current working directory, but note that this warning will
        become a fatal error in future CMake releases.


      Traceback (most recent call last):
        File "C:\Users\10537\AppData\Local\Temp\pip-install-kr487q86\amazon-ion_ae72437b5ff045c299c17f4f2c51981a\install.py", line 96, in _download_ionc
          _build_ionc()
        File "C:\Users\10537\AppData\Local\Temp\pip-install-kr487q86\amazon-ion_ae72437b5ff045c299c17f4f2c51981a\install.py", line 109, in _build_ionc
          _build_ionc_win()
        File "C:\Users\10537\AppData\Local\Temp\pip-install-kr487q86\amazon-ion_ae72437b5ff045c299c17f4f2c51981a\install.py", line 127, in _build_ionc_win
          check_call('cmake -G \"Visual Studio 17 2022\"')
        File "D:\ProgramData\Anaconda3\lib\subprocess.py", line 364, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command 'cmake -G "Visual Studio 17 2022"' returned non-zero exit status 1.

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "D:\ProgramData\Anaconda3\lib\shutil.py", line 620, in _rmtree_unsafe
          os.rmdir(path)
      PermissionError: [WinError 32] 另一个程序正在使用此文件，进程无法访问。: 'C:\\Users\\10537\\AppData\\Local\\Temp\\pip-install-kr487q86\\amazon-ion_ae72437b5ff045c299c17f4f2c51981a\\ion-c'

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\10537\AppData\Local\Temp\pip-install-kr487q86\amazon-ion_ae72437b5ff045c299c17f4f2c51981a\setup.py", line 72, in <module>
          run_setup()
        File "C:\Users\10537\AppData\Local\Temp\pip-install-kr487q86\amazon-ion_ae72437b5ff045c299c17f4f2c51981a\setup.py", line 23, in run_setup
          if C_EXT and _install_ionc():
        File "C:\Users\10537\AppData\Local\Temp\pip-install-kr487q86\amazon-ion_ae72437b5ff045c299c17f4f2c51981a\install.py", line 197, in _install_ionc
          if not _download_ionc():
        File "C:\Users\10537\AppData\Local\Temp\pip-install-kr487q86\amazon-ion_ae72437b5ff045c299c17f4f2c51981a\install.py", line 102, in _download_ionc
          shutil.rmtree(_IONC_DIR, onerror=readonly_handler)
        File "D:\ProgramData\Anaconda3\lib\shutil.py", line 740, in rmtree
          return _rmtree_unsafe(path, onerror)
        File "D:\ProgramData\Anaconda3\lib\shutil.py", line 622, in _rmtree_unsafe
          onerror(os.rmdir, path, sys.exc_info())
        File "C:\Users\10537\AppData\Local\Temp\pip-install-kr487q86\amazon-ion_ae72437b5ff045c299c17f4f2c51981a\install.py", line 77, in readonly_handler
          func(path)
      PermissionError: [WinError 32] 另一个程序正在使用此文件，进程无法访问。: 'C:\\Users\\10537\\AppData\\Local\\Temp\\pip-install-kr487q86\\amazon-ion_ae72437b5ff045c299c17f4f2c51981a\\ion-c'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

python 版本会有限制吗？我尝试问了gpt，让我更新cmake。
