### ISSUE TITLE
can't handle a cookie key containing special characters

### ISSUE THREAD

**Issue by changtimwu** [yihong0618/Kindle_download_helper#110]
```
timwu@iei-SER0:~/Kindle_download_helper$ python kindle.py --cookie-file cookie.txt 
Traceback (most recent call last):
  File "kindle.py", line 5, in <module>
    main()
  File "/home/timwu/Kindle_download_helper/kindle_download_helper/cli.py", line 293, in main
    kindle.set_cookie_from_string(f.read())
  File "/home/timwu/Kindle_download_helper/kindle_download_helper/kindle.py", line 92, in set_cookie_from_string
    cj = self._parse_kindle_cookie(cookie_string)
  File "/home/timwu/Kindle_download_helper/kindle_download_helper/kindle.py", line 120, in _parse_kindle_cookie
    cookie.load(kindle_cookie)
  File "/usr/lib/python3.8/http/cookies.py", line 529, in load
    self.__parse_string(rawdata)
  File "/usr/lib/python3.8/http/cookies.py", line 593, in __parse_string
    self.__set(key, rval, cval)
  File "/usr/lib/python3.8/http/cookies.py", line 485, in __set
    M.set(key, real_value, coded_value)
  File "/usr/lib/python3.8/http/cookies.py", line 352, in set
    raise CookieError('Illegal key %r' % (key,))
http.cookies.CookieError: Illegal key 'AMCVS_7742037254C95E840A4C98A6@AdobeOrg'
```

This could be easily worked around by simply removing that key/value pair.

**Comment by yihong0618** [comment]
'${cookie}'
