### ISSUE TITLE
获取的下载列表中的所有书籍未能全部下载到本地

### ISSUE THREAD

**Issue by jatmiuw** [yihong0618/Kindle_download_helper#115]
获取的下载列表中包含6006本书籍，点击“下载全部”，提示“下载完成”后目标文件夹中仅有5973本书，请问为什么下载列表中所有书籍未能全部下载？

**Comment by yihong0618** [comment]
有些书是试读本，无法下载

**Comment by jatmiuw** [comment]
这6006本书都是个人文档，不包括试读本，理论上应该都可以下载吧？

**Comment by yihong0618** [comment]
不一定。

**Comment by yihong0618** [comment]
有可能你一些书是同名的，参考readme解除同名限制（可能得用 cli

**Comment by jatmiuw** [comment]
Traceback (most recent call last):
  File "D:\Kindle_download_helper-1.4\kindle.py", line 1, in <module>
    from kindle_download_helper import main
  File "D:\Kindle_download_helper-1.4\kindle_download_helper\__init__.py", line 1, in <module>
    from kindle_download_helper.cli import main
  File "D:\Kindle_download_helper-1.4\kindle_download_helper\cli.py", line 1, in <module>
    from kindle_download_helper.kindle import Kindle
  File "D:\Kindle_download_helper-1.4\kindle_download_helper\kindle.py", line 17, in <module>
    from mobi import extract
ModuleNotFoundError: No module named 'mobi'

**Comment by jatmiuw** [comment]
PS D:\Kindle_download_helper-1.4> python kindle.py ${session-id=457-9512862-6586610; ubid-acbcn=459-0416442-2359641; lc-acbcn=zh_CN; i18n-prefs=CNY; x-acbcn=GEwfMBCrRJI2f850cR9whC1YLsSneiNG; at-main=Atza|IwEBIP4KOgkuAyYd6sqfqzwBcN1F_xXese7FWnMc6QTiKKaRjJHSIgV5GJ3lnkR4o1drZm1ap8rLmEy94ufWkFAdTHROl_4u6gG2A-gf_s9e4_hxixD9VQdd20gZuj02tQnRQXW5GGaABsYSnYnlYRMVv2nohW3216ryfPAOgwStqsXE7MQTUy6NW6sXB_-pUXndPbvyBoL_LCaFuSUOETXRcvgM; sess-at-main="hI7Ug4NhYqCjREuOe1OTlzZ0IWTkDoT6gjKARpbL+Cw="; sst-main=Sst1|PQE9aJaIISw3EdPEqWTvCyWkCXvG93gXR352EY73h9BcdP_ZjD0m8TCPYV4nMmLivSQXTQa3zY-e8eQijBsMdC9Cq-4h3nD1rOJr9Yj9AyaD27qzhTQtmfqH2OFfw-oB0JDJ3OUQzxRVEBKIklESiIbLhy5OGqrqijV1SSxSSvItUgjOrbq6cG20berTJISg1JuIg8wczHflSAjh5LXjilBdJC4vffSauavqg64GKrm7Zx-5OYRTy9BaYoM0ElMwJjMieGnwPOau7IWlL5maInodlcRV6gDaJQKXxLVzxlt_p1I; s_cc=true; s_vnum=2111965829383&vn=2; JSESSIONID=F438CFACF7EEBE0120FB765F72F54F0A; s_nr=1679982652927-Repeat; s_dslv=1679982652929; s_sq=[[B]]; s_ppv=100; csm-hit=tb:1EAK5T7K44RXWMJPW0TR+s-T7JQ4VEK3A9GVCV7QDBR|1681198481674&t:1681198481674&adb:adblk_yes; session-token="X/4NDtGPLHEoXHdA8WOC/YQKp1wf8e5nilq0WT+C1fa2+f4B8zGAYETw2ppi1AlOtJZmwDMdHqtopJyxgLlOoUUjPQ8l0jdGJHQw10B+Ef1hOCrIFhwdDDDeJC0VAjy5doV6s7BvLVhzZZE8C999CzOX56651mlw9Llbwr4vnRmGzysP4BRv3NhHX/qLO4u+XUl37Ai/+JQt6CXvN9FZHTh7SyZ62MC6V+QprDTzoeBx4XBJjwPeyUN9qLpBoHP3Dqp4VCG75Ps="; session-id-time=2082787201l} ${g8qGG+0vv+0HkCCVFqo+Qg0pEa/0Bz1str6hjgDSdBnEAAAAAQAAAABkNQ2OcmF3AAAAAFgvVn10EP4nuL9RKfa6ow==} --cn --pdoc --resolve_duplicate_names
Amazon bot check detected, sleep 3 sec
Using default device serial Number: G090KB0374620J90
It will take some time to get all PDOC books list, please wait
get all books error: AUTHENTICATION_ERROR

请问为什么会出现get all books error: AUTHENTICATION_ERROR这个报错信息？报错后倒是开始正常下载PDOC books了....

**Comment by jatmiuw** [comment]
> PS D:\Kindle_download_helper-1.4> python kindle.py ${session-id=457-9512862-6586610; ubid-acbcn=459-0416442-2359641; lc-acbcn=zh_CN; i18n-prefs=CNY; x-acbcn=GEwfMBCrRJI2f850cR9whC1YLsSneiNG; at-main=Atza|IwEBIP4KOgkuAyYd6sqfqzwBcN1F_xXese7FWnMc6QTiKKaRjJHSIgV5GJ3lnkR4o1drZm1ap8rLmEy94ufWkFAdTHROl_4u6gG2A-gf_s9e4_hxixD9VQdd20gZuj02tQnRQXW5GGaABsYSnYnlYRMVv2nohW3216ryfPAOgwStqsXE7MQTUy6NW6sXB_-pUXndPbvyBoL_LCaFuSUOETXRcvgM; sess-at-main="hI7Ug4NhYqCjREuOe1OTlzZ0IWTkDoT6gjKARpbL+Cw="; sst-main=Sst1|PQE9aJaIISw3EdPEqWTvCyWkCXvG93gXR352EY73h9BcdP_ZjD0m8TCPYV4nMmLivSQXTQa3zY-e8eQijBsMdC9Cq-4h3nD1rOJr9Yj9AyaD27qzhTQtmfqH2OFfw-oB0JDJ3OUQzxRVEBKIklESiIbLhy5OGqrqijV1SSxSSvItUgjOrbq6cG20berTJISg1JuIg8wczHflSAjh5LXjilBdJC4vffSauavqg64GKrm7Zx-5OYRTy9BaYoM0ElMwJjMieGnwPOau7IWlL5maInodlcRV6gDaJQKXxLVzxlt_p1I; s_cc=true; s_vnum=2111965829383&vn=2; JSESSIONID=F438CFACF7EEBE0120FB765F72F54F0A; s_nr=1679982652927-Repeat; s_dslv=1679982652929; s_sq=[[B]]; s_ppv=100; csm-hit=tb:1EAK5T7K44RXWMJPW0TR+s-T7JQ4VEK3A9GVCV7QDBR|1681198481674&t:1681198481674&adb:adblk_yes; session-token="X/4NDtGPLHEoXHdA8WOC/YQKp1wf8e5nilq0WT+C1fa2+f4B8zGAYETw2ppi1AlOtJZmwDMdHqtopJyxgLlOoUUjPQ8l0jdGJHQw10B+Ef1hOCrIFhwdDDDeJC0VAjy5doV6s7BvLVhzZZE8C999CzOX56651mlw9Llbwr4vnRmGzysP4BRv3NhHX/qLO4u+XUl37Ai/+JQt6CXvN9FZHTh7SyZ62MC6V+QprDTzoeBx4XBJjwPeyUN9qLpBoHP3Dqp4VCG75Ps="; session-id-time=2082787201l} ${g8qGG+0vv+0HkCCVFqo+Qg0pEa/0Bz1str6hjgDSdBnEAAAAAQAAAABkNQ2OcmF3AAAAAFgvVn10EP4nuL9RKfa6ow==} --cn --pdoc --resolve_duplicate_names Amazon bot check detected, sleep 3 sec Using default device serial Number: G090KB0374620J90 It will take some time to get all PDOC books list, please wait get all books error: AUTHENTICATION_ERROR
> 
> 请问为什么会出现get all books error: AUTHENTICATION_ERROR这个报错信息？报错后倒是开始正常下载PDOC books了....

但是下载完成后发现确实没有把所有个人文档列表中的书籍都下载下来....

**Comment by yihong0618** [comment]
你之前不是下载成功 5973 了么？

**Comment by jatmiuw** [comment]
> 你之前不是下载成功 5973 了么？
目前用cli只能下载到4317本书，请问为什么解除了同名限制后下载到的书籍数量反而更少呢？

**Comment by jatmiuw** [comment]
请问如何解决用cli下载时遇到get all books error: AUTHENTICATION_ERROR呢？

**Comment by yihong0618** [comment]
找一个好点的网络
目前没有精力提供解决方案，抱歉

**Comment by jatmiuw** [comment]
好的，感谢答复

yihong ***@***.***>于2023年4月24日 周一12:48写道：

**Comment by yihong0618** [comment]
因为这个是因为你的书太多了，其实用 GUI 也一样，超时会触发 AUTHENTICATION_ERROR. 没太好的办法目前。

**Comment by jatmiuw** [comment]
原来如此，明白了。谢谢！

yihong ***@***.***>于2023年4月24日 周一13:12写道：
