### ISSUE TITLE
Fail to download with `AUTHENTICATION_ERROR`

### ISSUE THREAD

**Issue by marek22k** [yihong0618/Kindle_download_helper#117]
Hello,

somehow the program does not work for me. I have taken the cookie via `document.cookie` and the token from the source code. After that I executed the program. Then a browser with Amazon appears, where my books can be seen and on the console the following message appears:

```
$python3 kindle.py "[string]" --cookie "'session-id=[string]; lc-acbde=en_GB; ubid-acbde=string; session-token=[long string]; x-acbde="[string]"; session-id-time=2082787201l; i18n-prefs=EUR; csm-hit=adb:adblk_yes&t:1680513188675&tb:D88PY5T4G6CM1YWRDQR2+s-D88PY5T4G6CM1YWRDQR2|1680513188675'" --de --dedrm
Opening the url to get cookie...You can wait for the page to finish loading and retry
Traceback (most recent call last):
  File "/home/marek/Downloads/Kindle_download_helper/kindle.py", line 5, in <module>
    main()
  File "/home/marek/Downloads/Kindle_download_helper/kindle_download_helper/cli.py", line 317, in main
    kindle.download_books(
  File "/home/marek/Downloads/Kindle_download_helper/kindle_download_helper/kindle.py", line 529, in download_books
    device = self.find_device()
  File "/home/marek/Downloads/Kindle_download_helper/kindle_download_helper/kindle.py", line 130, in find_device
    devices = self.get_devices()
  File "/home/marek/Downloads/Kindle_download_helper/kindle_download_helper/kindle.py", line 228, in get_devices
    raise Exception(
Exception: Error: AUTHENTICATION_ERROR, please visit https://www.amazon.de/hz/mycd/myx#/home/content/booksAll to revoke the csrftoken and cookie
```

**Comment by yihong0618** [comment]
python3 kindle.py ${csrf_coken} --cookie '${cookie}'

csrf token you can found in html.

Try just keeping the single quotes。
![image](https://user-images.githubusercontent.com/15976103/229476114-c5d483e8-4e58-45e3-ad3f-123192f571d9.png)

**Comment by marek22k** [comment]
The same thing happens with single quote characters. I will try it again tonight on another PC.

**Comment by yihong0618** [comment]
maybe our problem let us check.

**Comment by marek22k** [comment]
I have now tried it again on another computer and get either the same message or the following:
```
Traceback (most recent call last):
  File "/home/marek/Downloads/Kindle_download_helper/kindle.py", line 5, in <module>
    main()
  File "/home/marek/Downloads/Kindle_download_helper/kindle_download_helper/cli.py", line 317, in main
    kindle.download_books(
  File "/home/marek/Downloads/Kindle_download_helper/kindle_download_helper/kindle.py", line 529, in download_books
    device = self.find_device()
  File "/home/marek/Downloads/Kindle_download_helper/kindle_download_helper/kindle.py", line 130, in find_device
    devices = self.get_devices()
  File "/home/marek/Downloads/Kindle_download_helper/kindle_download_helper/kindle.py", line 224, in get_devices
    r.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: https://www.amazon.de/hz/mycd/ajax
```

**Comment by marek22k** [comment]
Just to make sure CSRF token I need to extract from following block:
```

                window.P.register('cf');
                var csrfToken = "[some string]";
                var startTime = "1681236803089";
                var devicePageLoadStartTime = "";
```

**Comment by chipbite** [comment]
Hi! I have the same issue. Trying on amazon.com, not .de.

I logged in, went to book list page and found the csrf token in the source, exactly like @marek22k posted in the post just above this one (there are just double quotes, no single quotes).

I then ran (saw it opening some pages in my browser), with the token in the clipboard, 

```
c:\temp\kindle\Kindle_download_helper>python kindle.py
Opening the url to get cookie...You can wait for the page to finish loading and retry
Traceback (most recent call last):
  File "c:\temp\kindle\Kindle_download_helper\kindle.py", line 5, in <module>
    main()
  File "c:\temp\kindle\Kindle_download_helper\kindle_download_helper\cli.py", line 318, in main
    kindle.download_books(
  File "c:\temp\kindle\Kindle_download_helper\kindle_download_helper\kindle.py", line 529, in download_books
    device = self.find_device()
             ^^^^^^^^^^^^^^^^^^
  File "c:\temp\kindle\Kindle_download_helper\kindle_download_helper\kindle.py", line 130, in find_device
    devices = self.get_devices()
              ^^^^^^^^^^^^^^^^^^
  File "c:\temp\kindle\Kindle_download_helper\kindle_download_helper\kindle.py", line 214, in get_devices
    self.ensure_cookie_token()
  File "c:\temp\kindle\Kindle_download_helper\kindle_download_helper\kindle.py", line 187, in ensure_cookie_token
    self._csrf_token = self._get_csrf_token()
                       ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\temp\kindle\Kindle_download_helper\kindle_download_helper\kindle.py", line 157, in _get_csrf_token
    raise Exception(
Exception: Can't get the csrf token, please refresh the page at https://www.amazon.com/hz/mycd/myx#/home/content/booksAll and retry
```

And then I tried again - now with csrftoken as commandline parameter, and added just `list` command. Similar result:

```
c:\temp\kindle\Kindle_download_helper>python kindle.py --list g9LLQDuP3BkFiwt27MflmigzW10y2azRkIDthfXlk+YoAAAAAQAAAABktnuIcmF3AAAAAFgvVn10EP4nuL9RKfa6ow==
Opening the url to get cookie...You can wait for the page to finish loading and retry
Traceback (most recent call last):
  File "c:\temp\kindle\Kindle_download_helper\kindle.py", line 5, in <module>
    main()
  File "c:\temp\kindle\Kindle_download_helper\kindle_download_helper\cli.py", line 301, in main
    kindle.get_devices()
  File "c:\temp\kindle\Kindle_download_helper\kindle_download_helper\kindle.py", line 228, in get_devices
    raise Exception(
Exception: Error: AUTHENTICATION_ERROR, please visit https://www.amazon.com/hz/mycd/myx#/home/content/booksAll to revoke the csrftoken and cookie
```

Two questions:
1. I do not have a kindle device. So I cannot use the cookie parameter - is that correct?
2. I have already logged in, and I get the csrftoken - and it opens web pages successfully it seems. So I guess: I dont need to worry about the authentication step as that is already done, correct?

I will try and see if I get a new token, and try again...

**Comment by chipbite** [comment]
Tried again with new token, same result.

Also tried with the token in quotes, same result...

```
c:\temp\kindle\Kindle_download_helper>python kindle.py --list "gx/aCaRlGa28bb7V6CoQKyg9tooNzJiNB0wDlXDAk+9QAAAAAQAAAABktoB5cmF3AAAAAFgvVn10EP4nuL9RKfa6ow=="
Opening the url to get cookie...You can wait for the page to finish loading and retry
Traceback (most recent call last):
  File "c:\temp\kindle\Kindle_download_helper\kindle.py", line 5, in <module>
    main()
  File "c:\temp\kindle\Kindle_download_helper\kindle_download_helper\cli.py", line 301, in main
    kindle.get_devices()
  File "c:\temp\kindle\Kindle_download_helper\kindle_download_helper\kindle.py", line 228, in get_devices
    raise Exception(
Exception: Error: AUTHENTICATION_ERROR, please visit https://www.amazon.com/hz/mycd/myx#/home/content/booksAll to revoke the csrftoken and cookie
```


Any tips appreciated!!

**Comment by yihong0618** [comment]
> Tried again with new token, same result.
> 
> Also tried with the token in quotes, same result...
> 
> ```
> c:\temp\kindle\Kindle_download_helper>python kindle.py --list "gx/aCaRlGa28bb7V6CoQKyg9tooNzJiNB0wDlXDAk+9QAAAAAQAAAABktoB5cmF3AAAAAFgvVn10EP4nuL9RKfa6ow=="
> Opening the url to get cookie...You can wait for the page to finish loading and retry
> Traceback (most recent call last):
>   File "c:\temp\kindle\Kindle_download_helper\kindle.py", line 5, in <module>
>     main()
>   File "c:\temp\kindle\Kindle_download_helper\kindle_download_helper\cli.py", line 301, in main
>     kindle.get_devices()
>   File "c:\temp\kindle\Kindle_download_helper\kindle_download_helper\kindle.py", line 228, in get_devices
>     raise Exception(
> Exception: Error: AUTHENTICATION_ERROR, please visit https://www.amazon.com/hz/mycd/myx#/home/content/booksAll to revoke the csrftoken and cookie
> ```
> 
> Any tips appreciated!!

python no_kindle.py -e ${email} -p ${password} —com to try？

**Comment by applebyter** [comment]
I've hacked your tool to work with AmazonAU. If I get it working correctly, I'll fork and make a pull request.

Regarding this issue I was getting the same authentication error until I put a single quote around the cookies, and copied all the cookies from Chrome.

`python no_kindle.py -e ${email} -p ${password} --au` gives a connection timeout failure.

`python kindle.py ${csrfToken} --cookie '${cookies} --au --list` retrieves the list of books.

`python kindle.py ${csrfToken} --cookie '${cookies}' --au` gives a 404 error for every book.

- Note that a single quote was required around all the cookies reported by Chrome. Trying to just pass the session-id cookie failed to authenticate.

**Comment by yihong0618** [comment]
> I've hacked your tool to work with AmazonAU. If I get it working correctly, I'll fork and make a pull request.
> 
> Regarding this issue I was getting the same authentication error until I put a single quote around the cookies, and copied all the cookies from Chrome.
> 
> `python no_kindle.py -e ${email} -p ${password} --au` gives a connection timeout failure.
> 
> `python kindle.py ${csrfToken} --cookie '${cookies} --au --list` retrieves the list of books.
> 
> `python kindle.py ${csrfToken} --cookie '${cookies}' --au` gives a 404 error for every book.
> 
> - Note that a single quote was required around all the cookies reported by Chrome. Trying to just pass the session-id cookie failed to authenticate.
> 

amazon close that
you can try no-kindle
