### ISSUE TITLE
客户端下载问题

### ISSUE THREAD

**Issue by flongar** [yihong0618/Kindle_download_helper#120]
ERROR - get devices failed
Traceback (most recent call last):
  File "kindle_gui.py", line 54, in run
  File "kindle_download_helper\kindle.py", line 225, in get_devices
  File "requests\models.py", line 1021, in raise_for_status
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: https://www.amazon.cn/hz/mycd/ajax

**Comment by yihong0618** [comment]
@flongar 暂时挂了，可能是亚马逊原因

**Comment by flongar** [comment]
好吧，看来目前只能手动下载了

**Comment by yihong0618** [comment]
恢复了应该
