### ISSUE TITLE
获取下载列表报错

### ISSUE THREAD

**Issue by qqiu** [yihong0618/Kindle_download_helper#122]
获取下载列表时报错：
Traceback (most recent call last):
  File "kindle_gui.py", line 177, in on_fetch_books
  File "kindle_gui.py", line 178, in <listcomp>
KeyError: 'authors'

**Comment by yihong0618** [comment]
@qqiu 是 pdoc 还是 ebook?

**Comment by qqiu** [comment]
ebook

**Comment by yihong0618** [comment]
@qqiu 用最新版本试试？
