### ISSUE TITLE
无设备脚本运行报错，requests.exceptions.SSLError:

### ISSUE THREAD

**Issue by Charlie-king** [yihong0618/Kindle_download_helper#135]
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\book\Kindle_download_helper\no_kindle.py", line 5, in <module>
    no_main()
  File "F:\book\Kindle_download_helper\kindle_download_helper\no_cli.py", line 100, in no_main
    nk = NoKindle(options.email, options.password, options.domain)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\book\Kindle_download_helper\kindle_download_helper\no_kindle.py", line 88, in __init__
    self.tokens = amazon_api.login(email, password, domain)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\book\Kindle_download_helper\kindle_download_helper\amazon_api.py", line 152, in login
    "user_context_map": {"frc": generate_frc(device_id)},
                                ^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\book\Kindle_download_helper\kindle_download_helper\amazon_api.py", line 100, in generate_frc
    "IpAddress": requests.get("https://api.ipify.org").text,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jin\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jin\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jin\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\book\Kindle_download_helper\kindle_download_helper\no_kindle.py", line 40, in new_send
    return old_send(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jin\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jin\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.ipify.org', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)')))

**Comment by yihong0618** [comment]
把 proxy 去掉试试

**Comment by yihong0618** [comment]
没问题我先关掉了，欢迎随时重开。
