### ISSUE TITLE
python no_kindle.py -e ${} -p ${} --cn 报错，不知道是什么情况，并不是网络问题，也没有开代理

### ISSUE THREAD

**Issue by zhmfalove** [yihong0618/Kindle_download_helper#138]
`Authenticating . . .
{"response": {"challenge": {"challenge_reason": "InvalidAuthenticationData", "uri": "https://www.amazon.cn/ap/challenge?arb=2b84eabc-6534-48f9-8bc6-81bf47a2a864", "required_authentication_method": "GenericClaimPassword"}}, "request_id": "be4211bb19cc4fd284b4367445de9f39"}
Could not retrieve auth tokens
Traceback (most recent call last):
  File "D:\Kindle_download_helper\no_kindle.py", line 5, in <module>
    no_main()
  File "D:\Kindle_download_helper\kindle_download_helper\no_cli.py", line 120, in no_main
    nk.make_library()
  File "D:\Kindle_download_helper\kindle_download_helper\no_kindle.py", line 167, in make_library
    r = self.session.send(
  File "D:\Kindle_download_helper\kindle_download_helper\no_kindle.py", line 45, in new_send
    return old_send(*args, **kwargs)
  File "D:\Software\anaconda3\lib\site-packages\requests\sessions.py", line 682, in send
    kwargs["proxies"] = resolve_proxies(request, self.proxies, self.trust_env)
  File "D:\Software\anaconda3\lib\site-packages\requests\utils.py", line 874, in resolve_proxies
    url = request.url
AttributeError: 'NoneType' object has no attribute 'url'`

这个问题一直都没有解决

**Comment by yihong0618** [comment]
@zhmfalove 

https://github.com/yihong0618/Kindle_download_helper/issues/134#issuecomment-1630043651 参考这个，然后
rm .tokens .device_id  .device_id.com .tokens.com 再跑一遍试试？

**Comment by zhmfalove** [comment]
@yihong0618 好的哈，感谢作者的辛苦付出。我昨天在notebook上运行是能成功的，且能正常下载，但可能解决同名文件重名问题上好像no_kindle.py不支持，但是kindle.py的下载我又一直都没成功，今晚试一下。

**Comment by zhmfalove** [comment]
@yihong0618 删除那几个还是不行，没有.tokens  和 .tokens.com，只删除了.device_id .device_id.com这两个文件

**Comment by afonw** [comment]
检查过了没有2FA 梯子直通 kindle.py --cn能列表但是无法下载 no_kindle.py --cn和贴主一样的报错
