### ISSUE TITLE
no_kindle.py 下载报错

### ISSUE THREAD

**Issue by baei2048** [yihong0618/Kindle_download_helper#150]
Authenticating . . .
Traceback (most recent call last):
  File "D:\code_project\Kindle_download_helper\kindle_download_helper\no_kindle.py", line 634, in download_all_ebooks
    self.download_book(b["ASIN"])
  File "D:\code_project\Kindle_download_helper\kindle_download_helper\no_kindle.py", line 428, in download_book
    self._download_kfx(manifest, asin)
  File "D:\code_project\Kindle_download_helper\kindle_download_helper\no_kindle.py", line 517, in _download_kfx
    "X-ADP-Reason": str(manifest["responseContext"]["reason"]),
KeyError: 'reason'
'reason'
请问是什么问题？

**Comment by yihong0618** [comment]
will take a look

**Comment by yihong0618** [comment]
@baei2048 fixed
