### ISSUE TITLE
no_kindle.py 运行后报错The server has encountered a runtime error

### ISSUE THREAD

**Issue by U11Leung** [yihong0618/Kindle_download_helper#172]
C:\Users\liang\Kindle_download_helper>python no_kindle.py -e xxx@xxx.com -p xxxxxxxx
Authenticating . . .
{"response": {"error": {"code": "ServerError", "index": "xxxxxxxxxxxxxxxxxxx", "message": "The server has encountered a runtime error."}}, "request_id": "xxxxxxxxxx"}
Could not retrieve auth tokens
Traceback (most recent call last):
  File "C:\Users\liang\Kindle_download_helper\no_kindle.py", line 5, in <module>
    no_main()
  File "C:\Users\liang\Kindle_download_helper\kindle_download_helper\no_cli.py", line 126, in no_main
    nk.make_library()
  File "C:\Users\liang\Kindle_download_helper\kindle_download_helper\no_kindle.py", line 167, in make_library
    r = self.session.send(
        ^^^^^^^^^^^^^^^^^^
  File "C:\Users\liang\Kindle_download_helper\kindle_download_helper\no_kindle.py", line 45, in new_send
    return old_send(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\liang\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\sessions.py", line 684, in send
    kwargs["proxies"] = resolve_proxies(request, self.proxies, self.trust_env)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\liang\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\utils.py", line 876, in resolve_proxies
    url = request.url
          ^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'url'

--------------------------------------------------------------

我看没有人贴出过这个报错，最一开始是会报错这个：
......
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

--------------------------------------------------------------

如果我特意输入错误的用户名/密码，可以见到返回了期望的AuthenticationFailed。。所以到服务器的连接应该是正常的

**Comment by yihong0618** [comment]
在设置安全里面重新登陆一次

**Comment by U11Leung** [comment]
是不是要在手机什么app上做？网页上不知道在哪里

**Comment by yihong0618** [comment]
> 是不是要在手机什么app上做？网页上不知道在哪里

在手机上同一网络登陆一遍

**Comment by U11Leung** [comment]
手机上，浏览器打开网页来登录？

**Comment by U11Leung** [comment]
手机上，浏览器打开网页来登录之后，电脑重新执行命令，报错不变

**Comment by dawnwind** [comment]
碰到同样的错误

**Comment by yihong0618** [comment]
> 碰到同样的错误

手机同网络登陆下试试。如果不行的话被风控了。应该不太行了

**Comment by U11Leung** [comment]
还是说亚马逊已经关掉这个API什么的了

**Comment by dawnwind** [comment]
> > 碰到同样的错误
> 
> 手机同网络登陆下试试。如果不行的话被风控了。应该不太行了

同网络也不行。看来只能用pc下完去calibre dedrm了。请问您今天更新的和这个问题相关吗

**Comment by yihong0618** [comment]
没关系😑

**Comment by U11Leung** [comment]
不用这个no_kindle 没有kindle硬件 还有其他什么方法？

**Comment by bk1412** [comment]
> > 碰到同样的错误
> 
> 手机同网络登陆下试试。如果不行的话被风控了。应该不太行了

同样遇到这个错误，如果账号密码的形式会有风控问题，不知道no_kindle模式是否可以尝试同样使用cookie的方式？
