### ISSUE TITLE
最新版能获取下载列表，但无法下载书籍，报错 get_devices KeyError: 'devices'

### ISSUE THREAD

**Issue by frawang** [yihong0618/Kindle_download_helper#181]
[2024-12-10 19:54:13,316]ERROR - get devices failed
Traceback (most recent call last):
  File "kindle_gui.py", line 54, in run
  File "kindle_download_helper\kindle.py", line 231, in get_devices
KeyError: 'devices'

**Comment by yihong0618** [comment]
因为你没有实体设备，得用 no_kindle

**Comment by yihong0618** [comment]
> > 因为你没有实体设备，得用 no_kindle
> 
> 您好！我有实体设备的，12月初还有成功下载过，是昨晚发现不行的。
> 
> ![image](https://private-user-images.githubusercontent.com/4443352/394522980-a40ae387-8280-4533-a0f2-243248cedb81.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4ODAwOTEsIm5iZiI6MTczMzg3OTc5MSwicGF0aCI6Ii80NDQzMzUyLzM5NDUyMjk4MC1hNDBhZTM4Ny04MjgwLTQ1MzMtYTBmMi0yNDMyNDhjZWRiODEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMTFUMDExNjMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Nzk0ZjljNTRmZjNhMzkwZWQ3ZjM4YzlhYTdiZDY5MmNjNWU0OTY5YjI3NDRjNzU5NmMwNmRlMDc2NDM3ZmZmYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.4bxAuyCQrh7Myj8-RWddWA2aQHDmkg6b8I77VFcTcY4)

用的是哪种方式？

**Comment by yihong0618** [comment]
好的我看看，图片我删了，里面可能有隐私
