### ISSUE TITLE
Mac下报错

### ISSUE THREAD

**Issue by emacsist** [yihong0618/Kindle_download_helper#26]
```python
Traceback (most recent call last):
  File "/private/tmp/Kindle_download_helper/kindle.py", line 284, in <module>
    kindle.set_cookie_from_browser()
  File "/private/tmp/Kindle_download_helper/kindle.py", line 69, in set_cookie_from_browser
    self.set_cookie(browsercookie.load())
  File "/opt/homebrew/lib/python3.9/site-packages/browsercookie/__init__.py", line 461, in load
    for cookie in sorted(_get_cookies(), key=lambda cookie: cookie.expires):
  File "/opt/homebrew/lib/python3.9/site-packages/browsercookie/__init__.py", line 451, in _get_cookies
    for cookie in klass().get_cookies():
  File "/opt/homebrew/lib/python3.9/site-packages/browsercookie/__init__.py", line 128, in get_cookies
    my_pass = my_pass.encode('utf8')
AttributeError: 'NoneType' object has no attribute 'encode'
```

**Comment by emacsist** [comment]
解决了. 是cookie没设置好. 按 readme 里的说明, 手动显式设置就可以了. 感谢作者
