### ISSUE TITLE
复制了csrfToken后，提示无效

### ISSUE THREAD

**Issue by figozhu** [yihong0618/Kindle_download_helper#38]
```bash
Traceback (most recent call last):
  File "kindle.py", line 311, in <module>
    kindle.set_cookie_from_browser()
  File "kindle.py", line 74, in set_cookie_from_browser
    self.set_cookie(browser_cookie3.load())
  File "kindle.py", line 70, in set_cookie
    raise Exception("Please make sure your amazon cookie is right")
Exception: Please make sure your amazon cookie is right
```

**Comment by figozhu** [comment]
页面每次刷新csrfToken都会变

**Comment by frostming** [comment]
这个报错是cookie问题，你 是否在浏览器中已经登录了亚马逊？浏览器是什么？

> 页面每次刷新csrfToken都会变

是的，服务端生成的

**Comment by figozhu** [comment]
> 这个报错是cookie问题，你 是否在浏览器中已经登录了亚马逊？浏览器是什么？
> 
> > 页面每次刷新csrfToken都会变
> 
> 是的，服务端生成的

命令行下运行的：

python3 kindle.py  csrfToken那串 --cn

**Comment by bladewang** [comment]
@figozhu 如果不是本机 cookie ，可以试试用最新的版本，命令只传 cookie 参数试一下（csrf_token 程序会自动更新的）

**Comment by ding** [comment]
> 

mac amacon-japan, 也遇到了一样的问题，只传cookie也尝试了，依然是 
raise Exception("Please make sure your amazon cookie is right")
