### ISSUE TITLE
No module named 'Cryptodome'

### ISSUE THREAD

**Issue by ZoomQuiet** [yihong0618/Kindle_download_helper#39]
使用环境:
```
     active environment : base
    active env location : /opt/homebrew/Caskroom/miniconda/base
            shell level : 1
       user config file : /Users/zoomq/.condarc
 populated config files : /Users/zoomq/.condarc
          conda version : 4.13.0
    conda-build version : not installed
         python version : 3.9.12.final.0
       virtual packages : __osx=10.16=0
                          __unix=0=0
                          __archspec=1=arm64
       base environment : /opt/homebrew/Caskroom/miniconda/base  (writable)
      conda av data dir : /opt/homebrew/Caskroom/miniconda/base/etc/conda
  conda av metadata url : None
           channel URLs : http://mirrors.aliyun.com/anaconda/pkgs/main/osx-arm64
                          http://mirrors.aliyun.com/anaconda/pkgs/main/noarch
                          http://mirrors.aliyun.com/anaconda/pkgs/r/osx-arm64
                          http://mirrors.aliyun.com/anaconda/pkgs/r/noarch
                          http://mirrors.aliyun.com/anaconda/pkgs/msys2/osx-arm64
                          http://mirrors.aliyun.com/anaconda/pkgs/msys2/noarch
                          https://repo.anaconda.com/pkgs/main/osx-arm64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-arm64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/osx-arm64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : /opt/homebrew/Caskroom/miniconda/base/pkgs
                          /Users/zoomq/.conda/pkgs
       envs directories : /opt/homebrew/Caskroom/miniconda/base/envs
                          /Users/zoomq/.conda/envs
               platform : osx-arm64
             user-agent : conda/4.13.0 requests/0.14.0 CPython/3.9.12 Darwin/21.5.0 OSX/10.16
                UID:GID : 502:20
             netrc file : /Users/zoomq/.netrc
           offline mode : False
```
运行时, 报错
```

$  python kindle.py "g64ylkP6TO8veBU4qV1F66RSDp7iEl0FMV06DqAIz8NFAAAAAQAAAABiowG+cmF3AAAAAFgvVn10EP4nuL9RKfa6ow==" --cn

Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/browsercookie/__init__.py", line 30, in <module>
    from Cryptodome.Protocol.KDF import PBKDF2
ModuleNotFoundError: No module named 'Cryptodome'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/zoomq/Downloads/_kindle/Kindle_download_helper-0.3.1/kindle.py", line 14, in <module>
    import browsercookie
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/browsercookie/__init__.py", line 33, in <module>
    from Crypto.Protocol.KDF import PBKDF2
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/Crypto/Protocol/KDF.py", line 32, in <module>
    from Crypto.Hash import SHA1, SHA256, HMAC, CMAC, BLAKE2s
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/Crypto/Hash/SHA1.py", line 29, in <module>
    _raw_sha1_lib = load_pycryptodome_raw_lib("Crypto.Hash._SHA1",
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/Crypto/Util/_raw_api.py", line 309, in load_pycryptodome_raw_lib
    raise OSError("Cannot load native module '%s': %s" % (name, ", ".join(attempts)))
OSError: Cannot load native module 'Crypto.Hash._SHA1': Not found '_SHA1.cpython-39-darwin.so', Cannot load '_SHA1.abi3.so': cannot load library '/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/Crypto/Util/../Hash/_SHA1.abi3.so': dlopen(/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/Crypto/Util/../Hash/_SHA1.abi3.so, 0x0002): tried: '/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/Crypto/Util/../Hash/_SHA1.abi3.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/Crypto/Hash/_SHA1.abi3.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')).  Additionally, ctypes.util.find_library() did not manage to locate a library called '/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/Crypto/Util/../Hash/_SHA1.abi3.so', Not found '_SHA1.so'
```

**Comment by ZoomQuiet** [comment]
![](https://ipic.zoomquiet.top/2022-06-10-zshot%202022-06-10%2016.41.30.jpg)
转换思路, 用 pip uninstall 相关模块, 使用 conda install
获得正确可用加密模块
