### ISSUE TITLE
执行的时候提示list index out of range，请问是什么问题？

### ISSUE THREAD

**Issue by tanqimin** [yihong0618/Kindle_download_helper#44]
`Traceback (most recent call last):
  File "D:\download\Kindle_download_helper-main\kindle.py", line 328, in <module>
    kindle.download_books(start_index=options.index - 1, filetype=options.filetype)
  File "D:\download\Kindle_download_helper-main\kindle.py", line 237, in download_books
    device = self.get_devices()[0]
IndexError: list index out of range`

**Comment by frostming** [comment]
这应该是你没有设备？

**Comment by tanqimin** [comment]
> 

的确是的，我绑定了设备就可以了，谢谢
