### ISSUE TITLE
新版本仍提示报错KeyError: 'items'

### ISSUE THREAD

**Issue by tmdt5217** [yihong0618/Kindle_download_helper#56]
客户端，输入后提示KeyError: 'items'，请问该怎么操作呢？

**Comment by zzhanghub** [comment]
同样的情况，测试了mac和win都是提示KeyError: 'items'

**Comment by yihong0618** [comment]
和 #57 一个情况。

**Comment by zzhanghub** [comment]
> 和 #57 一个情况。

这个重试了好多次啦，两个设备都不行呢。

**Comment by yihong0618** [comment]
如果是 items 的错一般是你买书了但没绑定设备。

ownership 读到了。
https://github.com/yihong0618/Kindle_download_helper/blob/main/kindle.py#L229

**Comment by tmdt5217** [comment]
> 
已绑定设备，还是不行

**Comment by zzhanghub** [comment]
> 如果是 items 的错一般是你买书了但没绑定设备。
> 
> ownership 读到了。 https://github.com/yihong0618/Kindle_download_helper/blob/main/kindle.py#L229

我也有几个kindle绑定的。

**Comment by pretenderlu** [comment]
> 如果是 items 的错一般是你买书了但没绑定设备。
> 
> ownership 读到了。 https://github.com/yihong0618/Kindle_download_helper/blob/main/kindle.py#L229

现在再试又变成这个了。。。
KeyError: 'OwnershipData'

**Comment by zzhanghub** [comment]
Traceback (most recent call last):
  File "kindle_download_helper.py", line 163, in on_fetch_books
  File "kindle.py", line 229, in get_all_books
KeyError: 'items'

**Comment by frostming** [comment]
请测试下 0.4.2 的release

**Comment by scegg** [comment]
0.4.2 windows版本已确认修复。
