### ISSUE TITLE
日亚下载出错

### ISSUE THREAD

**Issue by lykayang** [yihong0618/Kindle_download_helper#57]
windows 11 , chrome , kindle download helper 0.4
日亚

第一次，cookie 来自浏览器
提示
Traceback (most recent call last):
  File "kindle_download_helper.py", line 115, in setup_kindle
AttributeError: 'Kindle' object has no attribute 'set_cookie_from_browser'

第二次，cookie来自输入
提示
Traceback (most recent call last):
  File "kindle_download_helper.py", line 163, in on_fetch_books
  File "kindle.py", line 229, in get_all_books
KeyError: 'items'

感谢yihong!

**Comment by yihong0618** [comment]
增加 --jp 了没～？

**Comment by lykayang** [comment]
用的是0.4，已选JP登录 
有买了一本收费的

**Comment by pretenderlu** [comment]
中亚输入cookie，刷新列表也是显示KeyError: 'items'

**Comment by frostming** [comment]
KeyError: 'items' 已在 0.4.1中修复

**Comment by tmdt5217** [comment]
> 因为亚马逊限制了，多跑几次试试。

试几次都不行

**Comment by zzhanghub** [comment]
item问题，试了很多次了啦，三个设备都不可以～

**Comment by yihong0618** [comment]
@zzhanghub 也是日亚么？

**Comment by zzhanghub** [comment]
> 

中亚

**Comment by hakumai7** [comment]
> item问题，试了很多次了啦，三个设备都不可以～

有无绑定实体kindle设备？

**Comment by zzhanghub** [comment]
> > item问题，试了很多次了啦，三个设备都不可以～
> 
> 有无绑定实体kindle设备？

均已绑定

**Comment by lykayang** [comment]
中亚在0.3的时候是没问题的。现在没有再试。

windows 11 , chrome , kindle download helper 0.41，日亚
只绑了1个kindlw
中亚美亚均退出登录。

浏览器读cookie:
Traceback (most recent call last):
  File "kindle_download_helper.py", line 161, in on_fetch_books
  File "kindle.py", line 229, in get_all_books
KeyError: 'OwnershipData'

自行输入cookie
Traceback (most recent call last):
  File "kindle_download_helper.py", line 161, in on_fetch_books
  File "kindle.py", line 229, in get_all_books
KeyError: 'items'

**Comment by lykayang** [comment]
0.31读美亚也是没问题的。就是下载的书不能dedrm

**Comment by yihong0618** [comment]
收到，感谢。我们晚上看一下。

**Comment by frostming** [comment]
请测试下 0.4.2 的release

**Comment by frostming** [comment]
Duplicate with #56
