### ISSUE TITLE
一直报错ConnectionError

### ISSUE THREAD

**Issue by nuluee** [yihong0618/Kindle_download_helper#58]
0.4及0.41版本，chrome
无论是cmd还是gui版本都是这个错误（python设置问题？）

Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 703, in urlopen
  File "urllib3\connectionpool.py", line 386, in _make_request
  File "urllib3\connectionpool.py", line 1040, in _validate_conn
  File "urllib3\connection.py", line 395, in connect
  File "urllib3\util\ssl_.py", line 350, in create_urllib3_context
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\abc\\Desktop\\1\\sslkey.log'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 489, in send
  File "urllib3\connectionpool.py", line 785, in urlopen
  File "urllib3\util\retry.py", line 550, in increment
  File "urllib3\packages\six.py", line 769, in reraise
  File "urllib3\connectionpool.py", line 703, in urlopen
  File "urllib3\connectionpool.py", line 386, in _make_request
  File "urllib3\connectionpool.py", line 1040, in _validate_conn
  File "urllib3\connection.py", line 395, in connect
  File "urllib3\util\ssl_.py", line 350, in create_urllib3_context
urllib3.exceptions.ProtocolError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "kindle_download_helper.py", line 161, in on_fetch_books
  File "kindle.py", line 212, in get_all_books
  File "requests\sessions.py", line 635, in post
  File "requests\sessions.py", line 587, in request
  File "requests\sessions.py", line 701, in send
  File "requests\adapters.py", line 547, in send
requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 703, in urlopen
  File "urllib3\connectionpool.py", line 386, in _make_request
  File "urllib3\connectionpool.py", line 1040, in _validate_conn
  File "urllib3\connection.py", line 395, in connect
  File "urllib3\util\ssl_.py", line 350, in create_urllib3_context
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\abc\\Desktop\\1\\sslkey.log'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 489, in send
  File "urllib3\connectionpool.py", line 785, in urlopen
  File "urllib3\util\retry.py", line 550, in increment
  File "urllib3\packages\six.py", line 769, in reraise
  File "urllib3\connectionpool.py", line 703, in urlopen
  File "urllib3\connectionpool.py", line 386, in _make_request
  File "urllib3\connectionpool.py", line 1040, in _validate_conn
  File "urllib3\connection.py", line 395, in connect
  File "urllib3\util\ssl_.py", line 350, in create_urllib3_context
urllib3.exceptions.ProtocolError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "kindle_download_helper.py", line 161, in on_fetch_books
  File "kindle.py", line 212, in get_all_books
  File "requests\sessions.py", line 635, in post
  File "requests\sessions.py", line 587, in request
  File "requests\sessions.py", line 701, in send
  File "requests\adapters.py", line 547, in send
requests.exceptions.ConnectionError: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))

**Comment by yihong0618** [comment]
看起来是 ssl 问题。
