### ISSUE TITLE
Cannot download in Amazon JP with latest version

### ISSUE THREAD

**Issue by ruby109** [yihong0618/Kindle_download_helper#72]
```
python3 kindle.py --jp g9PkIMzDCFqekYV7hY*************1386DAAAAAQAAAABiyubhcmF3AAAAAFgvVn10EP4nuL9RKfa6ow==


Opening the url to get cookie...You can wait for the page to finish loading and retry
Traceback (most recent call last):
  File "/Users/l_shen/OpenSource/Kindle_download_helper/kindle.py", line 632, in <module>
    kindle.download_books(start_index=options.index - 1, filetype=options.filetype)
  File "/Users/l_shen/OpenSource/Kindle_download_helper/kindle.py", line 488, in download_books
    device = self.get_devices()[0]
  File "/Users/l_shen/OpenSource/Kindle_download_helper/kindle.py", line 248, in get_devices
    raise Exception(
```

Exception: Error: AUTHENTICATION_ERROR, please visit https://www.amazon.jp/hz/mycd/myx#/home/content/booksAll to revoke the csrftoken and cookie

Do I need to have a kindle reader or something? I've tried many ways like browser-cookie3 or refreshing amazon page mannully

**Comment by ruby109** [comment]
solve it with cookie file.
