### ISSUE TITLE
[feat] 导出笔记

### ISSUE THREAD

**Issue by yihong0618** [yihong0618/Kindle_download_helper#96]
但可能需要新的登陆方式。
考虑中。

**Comment by wjianbo** [comment]
考虑得怎么样了？

**Comment by yihong0618** [comment]
> 考虑得怎么样了？

已经支持了啊

**Comment by wjianbo** [comment]
哦哦！我去试试

**Comment by wjianbo** [comment]
不好意思想确认一下是用这条命令吗？
```
python no_kindle.py -e ${email} -p ${password} --memory
```
请问这个海外可以正常使用吗？我试着加了`--jp`貌似不行

输出了一下 request 的 body, url 和 header
```
Authenticating . . .
{'auth_data': {'use_global_authentication': 'true', 'user_id_password': {'password': '******', 'user_id': '******@gmail.com'}}, 'registration_data': {'domain': 'DeviceLegacy', 'device_type': 'A2A33MVZVPQKHY', 'device_serial': '9d4f6cd171613b623cbde581a54de652', 'app_name': 'com.iconology.comix', 'app_version': '1221328936', 'device_model': 'walleye/google/Pixel 2', 'os_version': 'google/walleye/walleye:8.1.0/OPM1.171019.021/4565141:user/release-keys', 'software_version': '1221328936'}, 'requested_token_type': ['bearer', 'mac_dms', 'store_authentication_cookie', 'website_cookies'], 'cookies': {'domain': 'amazon.co.jp', 'website_cookies': []}, 'user_context_map': {'frc': 'ADHI4ooWMlwhxusXRz1b2vjJMJzf5lb7fbOLS8cUWZAuQoBVEgsX3qyLIsM/007IgFTktaWSAfPW0+S3n/2qUeHfvmYVZC+vNu4dMPsiotW/bQLYK3AN0tLXxkULZOPKD/LMVYApzTmz3fl6gEy5brNzwirjIgVIFkAro1eXaSgHhZDWtxz2xjyUaM6zbTvjfqvGbClyslNerjlPrHL4gE1Kw8oNXWxUaOj3n7auxmi9dPelY4yD4D2dkBblw3ttjGbNX9ugGRmfAQ9qQbhbGLgHS7GFdTJU0HN86MRvDaKyns9UmhgcZNDYCXFin8H3HMk14HStAuIOV5i3wQu4BKPNfsAGt50w3kAqgjx/YpNznWPVN0t99lQ='}, 'device_metadata': {'device_os_family': 'android', 'device_type': 'A2A33MVZVPQKHY', 'device_serial': '9d4f6cd171613b623cbde581a54de652', 'mac_address': '1CC4A4BC6E6F6ACC7E659BAB92CC4C5D71A54167C0812A999E40A8A0925FEBB108E9401A2CF1219E95FD4DCFC4F9D43E5C6F1407115F3EA6AA3D9E599C72F550', 'manufacturer': 'Google', 'model': 'walleye/google/Pixel 2', 'os_version': '30', 'android_id': 'e97690019ccaab2b', 'product': 'walleye/google/Pixel 2'}, 'requested_extensions': ['device_info', 'customer_info']}
https://api.amazon.co.jp/auth/register
{'Accept-Charset': 'utf-8', 'User-Agent': 'Dalvik/2.1.0 (Linux; U; Android 10; Pixel 2 Build/OPM1.171019.021)', 'x-amzn-identity-auth-domain': 'api.amazon.co.jp', 'x-amzn-requestid': '29c65f07ce99461ab73cad125b018546'}
{"response": {"error": {"code": "ThrottledRequest", "message": "The request has been throttled."}}, "request_id": "f1bff872f3634390a1f2866ebfeb082f"}
Could not retrieve auth tokens
Traceback (most recent call last):
  File "/workspaces/Kindle_download_helper/no_kindle.py", line 5, in <module>
    no_main()
  File "/workspaces/Kindle_download_helper/kindle_download_helper/no_cli.py", line 126, in no_main
    nk.make_library()
  File "/workspaces/Kindle_download_helper/kindle_download_helper/no_kindle.py", line 167, in make_library
    r = self.session.send(
        ^^^^^^^^^^^^^^^^^^
  File "/workspaces/Kindle_download_helper/kindle_download_helper/no_kindle.py", line 45, in new_send
    return old_send(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/requests/sessions.py", line 684, in send
    kwargs["proxies"] = resolve_proxies(request, self.proxies, self.trust_env)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.local/lib/python3.11/site-packages/requests/utils.py", line 876, in resolve_proxies
    url = request.url
          ^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'url'
```

**Comment by yihong0618** [comment]
参考这个 https://github.com/yihong0618/Kindle_download_helper/issues/155

**Comment by wjianbo** [comment]
> 参考这个 #155

感谢！

最后尝试用 `--com --bookmark` 拿到了 `pdocs_bookmark.json` 文件，里面可以找到 highlight 记录。请问目前是只做到这一步，没有进一步获取相应内容的处理了对吧？

```json
  {
      "annotationId": "a4cece5fc-e0ad-45c9-866b-fb6484bc7832",
      "startPosition": "104247",
      "endPosition": "105002",
      "type": "kindle.highlight",
      "creationTime": "2024-10-13 23:31:40.0",
      "lastModificationTime": "2024-10-13 23:31:40.0"
  }
```

**Comment by yihong0618** [comment]
> 
> 
> 
> 
> 
> 
> > 参考这个 #155
> 
> 
> 
> 感谢！
> 
> 
> 
> 最后尝试用 `--com --bookmark` 拿到了 `pdocs_bookmark.json` 文件，里面可以找到 highlight 记录。请问目前是只做到这一步，没有进一步获取相应内容的处理了对吧？
> 
> 
> 
> ```json
> 
>   {
> 
>       "annotationId": "a4cece5fc-e0ad-45c9-866b-fb6484bc7832",
> 
>       "startPosition": "104247",
> 
>       "endPosition": "105002",
> 
>       "type": "kindle.highlight",
> 
>       "creationTime": "2024-10-13 23:31:40.0",
> 
>       "lastModificationTime": "2024-10-13 23:31:40.0"
> 
>   }
> 
> ```

进一步获取里面的内容是不可能的。

**Comment by wjianbo** [comment]
明白了，多谢！
